name: gatsby deploy

on:
  push:
    branches: gh-pages

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-18.04

    steps:
      - name: checkout code
        uses: actions/checkout@v1

      - name: packages install
        run: yarn install

      - name: gatsby build
        run: yarn build
        env:
          GH_API_KEY: ${{ secrets.ACTION }}

      - name: deploy
        uses: maxheld83/ghpages@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.ACTION }}
          BUILD_DIR: 'public/'
